version: "3.3"                          
                                        
services:                               
  app:                                  
    build: .                            
    command: python3 -m Adarsh          
    restart: on-failure                 
    ports:                              
      - "80:80"                         
